### ISSUE TITLE
01-environment Mac  mongodb 安装失败

### ISSUE THREAD

**Issue by zhang-zedong** [kenspirit/javascript-study-group#5]
我使用 homebrew 安装了 mongodb，而后在`mongod`启动异常，而是搜索了几篇教程，使用了
`sudo chown -R $USER /data/db`
终端显示连接数据库，然而通过`locolhost`不能打开。
![2016-12-17 10 23 29](https://cloud.githubusercontent.com/assets/16751212/21287526/b5aafcc0-c4a8-11e6-9dfc-2d6f942d3d36.png)
![2016-12-17 10 24 00](https://cloud.githubusercontent.com/assets/16751212/21287527/b95241a8-c4a8-11e6-8a93-159856c8437e.png)
![2016-12-17 10 22 32](https://cloud.githubusercontent.com/assets/16751212/21287528/bcb23056-c4a8-11e6-942f-b32eea0bf1dc.png)

**Comment by kenspirit** [comment]
@zhang-zedong 目前看你的 mongod 启动应该是没有问题的了。能够提供你 MongoChef 的配置吗？

或者你在命令行输入：`mongo` 看能不能登录？

**Comment by zhang-zedong** [comment]
问题解决！

输入`mongod`后
![2016-12-18 11 18 26](https://cloud.githubusercontent.com/assets/16751212/21294488/9382747c-c578-11e6-91fc-6251136e415a.png)

而后通过错误信息搜索，发现需要`sudo`权限，即`sodo mongod`。

![2016-12-18 11 18 44](https://cloud.githubusercontent.com/assets/16751212/21294497/c326b184-c578-11e6-97fc-fe0840ab9a58.png)
---
另外，感谢回复，本来挺简单的一个事儿。有人帮助的感觉给了我巨大行动动力。

**Comment by kenspirit** [comment]
这么奇怪，你已经 `sudo chown` 了啊。或者你可以试试 `sudo chmod -R 755 /data/db` 来更改文件夹属性。能不用 root 就尽量不用了。

**Comment by shaheming** [comment]
我的mac也遇见这样的情况 OSX Serra  
`sudo chmod 0755 /data/db`
用解决的

**Comment by kenspirit** [comment]
@shaheming 我在文档教程上面也加上这点了。先关了 Issue 吧。有问题再开。
