### ISSUE TITLE
02-boilerplate Mac 无法注册以及登录

### ISSUE THREAD

**Issue by zhang-zedong** [kenspirit/javascript-study-group#6]
点击注册登录都没有反应。
![2016-12-22 10 26 03](https://cloud.githubusercontent.com/assets/16751212/21413315/48de4368-c831-11e6-91c5-38153c56cdd6.png)
![2016-12-22 10 26 41](https://cloud.githubusercontent.com/assets/16751212/21413317/4a90b5e2-c831-11e6-934e-c0a3d4730b6c.png)

**Comment by kenspirit** [comment]
@zhang-zedong 看到上面有报错了吗？  EMAIL_NOT_UNIQUE。应该是有记录了。回头我看看报错那里是不是提示信息有问题，没能提示出来。

**Comment by kenspirit** [comment]
注册完应该是自动登录的，虽然暂时没有特别的页面。

**Comment by zhang-zedong** [comment]
我读到`EMAIL_NOT_UNIQUE`了，我尝试注册了好几个账号，点登录没反应，看看记录（最后一张截图最后一句，是`Unauthorized`。我试了一下才知道，做这个需要开`mongodb`。那什么时候需要开Redis呢？

**Comment by kenspirit** [comment]
@zhang-zedong 我改好了代码，你可以看我最新的 commit。现在就能在页面看到错误了。Redis 还没需要在一开始的时候用，后面等要用到缓存的时候才需要。项目启动都是需要开 mongodb，你没有开，应该启动都会出错的啊。
