### ISSUE TITLE
02-boilerplate node index.js 后无法登入（已开启mongod）

### ISSUE THREAD

**Issue by shaheming** [kenspirit/javascript-study-group#7]
![db](https://cloud.githubusercontent.com/assets/23076827/21565676/d658c88a-ced5-11e6-942a-e8f0143ffed5.png)
![development.js](https://cloud.githubusercontent.com/assets/23076827/21565677/e384946c-ced5-11e6-84fd-fdbf1082aed7.png)
![browser](https://cloud.githubusercontent.com/assets/23076827/21565735/5b9bc07e-ced6-11e6-98cc-9278dc8a1a71.png)
![server](https://cloud.githubusercontent.com/assets/23076827/21565748/868e8a32-ced6-11e6-9709-a0975a4fc8d7.png)

你好，按照流程启动了 node index.js 后 打开网页没有反应，请问是什么问题？

**Comment by kenspirit** [comment]
这个实在有点奇怪。从 console 看，服务器已经启动，也没有出错。数据库也应该是好的。

但是服务器好像就没有接受到你的请求。

有在 Chrome 设了代理什么的吗？其它浏览器有没有问题？用 `http://127.0.0.1:3000/` 呢？

如果还是不行，或者你可以联系我，然后你安装 TeamViewer，我帮你看看。

**Comment by shaheming** [comment]
问题解决了，就是代理的问题。我在mac上用了showdowsockes 开了全局代理模式，所以出了问题。😊谢谢~
