### ISSUE TITLE
02-boilerplate Mac 流程问题

### ISSUE THREAD

**Issue by shaheming** [kenspirit/javascript-study-group#8]
你好，我把所有的教程看了一遍，打算从头开始做一做，但是遇见了问题。按照我的理解是要将 generator-evergrow clone下来然后在里面用 `yo evergrow` 生成app. 输入命令后它提示是否要overwrite package.js 
**第一：**输入 y.
结果图是 
![screen shot 2016-12-31 at 15 20 49](https://cloud.githubusercontent.com/assets/23076827/21576491/cc3a9af8-cf6c-11e6-880a-2e5fe83b6590.png)
**第二：输入 n** 结果是
![screen shot 2016-12-31 at 15 20 18](https://cloud.githubusercontent.com/assets/23076827/21576495/ff9835ea-cf6c-11e6-989e-4d13ecf29a36.png)

请问是不是我的理解出了问题：
我的理解是要在这个generator-evergrow 文件夹里生成app
 `yo evergrow` 
然后调用
`yo evergrow:model Image`
来依次生model与controller等。

**Comment by kenspirit** [comment]
你有点误解了。你不需要 clone generator 的，你只是要使用它。根据 generator 上面的 [Readme](https://github.com/kenspirit/generator-evergrow) 进行安装。

```
npm install -g yo
npm install -g generator-evergrow
```

然后你新建一个项目文件夹，在里面再运行 `yo evergrow` 等命令生成 model, controller 等。

**Comment by shaheming** [comment]
哦哦明白了，但是我已经建好按照 [Readme](https://github.com/kenspirit/generator-evergrow) 执行完命令，新建了工程，想按照
[教程04](https://github.com/kenspirit/javascript-study-group/blob/master/tutorial/04-data-modeling.md)里面 
`yo evergrow:model Image`
命令生成model 却出现下面错误
![screen shot 2016-12-31 at 19 50 15](https://cloud.githubusercontent.com/assets/23076827/21577346/c31a91f0-cf92-11e6-927e-16f6a2ebea3b.png)

**Comment by kenspirit** [comment]
这么奇怪？那里有这个文件吗？

`/usr/local/lib/node_modules/generator-evergrow/common/moduleConstructor.js`

**Comment by shaheming** [comment]
![screen shot 2016-12-31 at 20 22 34](https://cloud.githubusercontent.com/assets/23076827/21577475/e36dcdc4-cf96-11e6-9ef7-33fafcae8a77.png)

**Comment by kenspirit** [comment]
我发现问题了，我本地使用和网络安装有点不同，我重新发一个新版本后告诉你。

**Comment by shaheming** [comment]
我看见你的仓库里[generator-evergrow](https://github.com/kenspirit/generator-evergrow)
有common 这个目录，但是我用npm安装的文件里面没有。
里面 [enerator-evergrow/generators/model/index.js](https://github.com/kenspirit/generator-evergrow/blob/master/generators/model/index.js) 
有加载 
`module '../../common/moduleConstructor'`

**Comment by shaheming** [comment]
好的谢谢😊

**Comment by kenspirit** [comment]
搞好了，你重新安装一下。

`npm install -g generator-evergrow@0.3.0`

**Comment by shaheming** [comment]
好了，问题model 可以正常生成了，谢谢~
